lib/annotamele/foundation/config/routes.rb
AnnotameLE::Application.routes.draw do
  devise_for :users

  root 'answers#question'

  get '/question', to: 'answers#question', as: 'new_question'
  post '/answer', to: 'answers#add_answer', as: 'new_answer'

  get '/export(.format)', to: 'answers#index', as: 'export'

  namespace :admin do
    root 'base#index'
    resources :users
    get '/config', to: 'config#index', as: 'config'
    post '/config/types', to: 'config#update_types', as: 'config_types'
    post '/config/questions', to: 'config#update_questions', as: 'config_questions'
    delete '/config', to: 'config#purge', as: 'purge_config'
  end
end

lib/annotamele/foundation/app/controllers/admin/config_controller.rb
module Admin
  class ConfigController < Admin::BaseController
    include AdminHelper
    def index
      @questions = Question.all
      @types = AnswerType.all # Rails.application.config.annotamele_types
    end

    def show
    end

    def update_types
      if params[:types_file] && load_types(params[:types_file])
        redirect_to admin_config_path, notice: 'Types were added'
      else
        redirect_to admin_config_path, alert: 'Types were NOT added. Wrong file format?'
      end
    end

    def update_questions
      if params[:questions_file] && load_questions(params[:questions_file])
        redirect_to admin_config_path, notice: 'Questions were added'
      else
        redirect_to admin_config_path, alert: 'Questions were NOT added. Wrong file format?'
      end
    end

    def purge
      Answer.delete_all
      Question.delete_all
      AnswerType.delete_all
      redirect_to admin_config_path, notice: 'All answers, questions and types were deleted'
    end
  end
end

lib/annotamele/foundation/app/views/admin/config/index.html.erb
<% title("Admin Config") %>
<ol class="breadcrumb">
  <li><%= link_to "Admin Panel", admin_root_path %></li>
  <li class="active">Config</li>
</ol>

<div role="tabpanel">
 <ul class="nav nav-tabs col-md-10" role="tablist">
    <li role="presentation" class="active">
      <a href="#types" aria-controls="types" role="tab" data-toggle="tab">Question Types <span class="badge"><%= @types.size %></span></a>
    </li>
    <li role="presentation">
      <a href="#questions" aria-controls="questions" role="tab" data-toggle="tab">Questions <span class="badge"><%= @questions.size %></span></a>
    </li>
  </ul>
  <%= link_to 'DELETE ALL', 
                admin_purge_config_path, 
                method: :delete, 
                data: { confirm: "Are you sure ?"},
                class: 'btn btn-danger pull-right' %>

  <div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="types">
      <br />
      <%= form_tag admin_config_types_path, multipart: true, class: 'form-inline' do -%>
        <div class="form-group">
          <label for="types_file">Add types</label>
          <%= file_field_tag 'types_file' %>
          <p class="help-block">JSON file with new question types</p>
        </div>
        
        <%= submit_tag 'Upload', class: 'btn btn-success' %>
      <% end -%>
      <br />
      <% @types.each do |type| %>
        <div class="col-md-6">
          <h4><span class="label label-info">ID: <%= type.id %></span> <span class="label label-primary"><%= type.export[:type] %></span></h4>
          <div class="panel panel-default">
            <div class="panel-body">
              <%= render type.view_partial %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="questions">
      <br />
      <%= form_tag admin_config_questions_path, multipart: true, class: 'form-inline' do -%>
        <div class="form-group">
          <label for="questions_file">Add questions</label>
          <%= file_field_tag 'questions_file' %>
          <p class="help-block">JSON file with new questions</p>
        </div>
        
        <%= submit_tag 'Upload', class: 'btn btn-success' %>
      <% end -%>
      <br />
      <% @questions.each do |q| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <dl class="dl-horizontal">
              <dt><strong>Object:</strong></dt>
              <dd><%= q.object %></dd>
              <dt><strong>Context:</strong></dt>
              <dd><%= q.context %></dd>
              <dt><strong>Type:</strong></dt>
              <dd><%= q.type_id %></dd>
            </dl>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>