lib/annotamele/foundation/config/routes.rb
AnnotameLE::Application.routes.draw do
  devise_for :users

  root 'answers#question'

  get '/question', to: 'answers#question', as: 'new_question'
  post '/answer', to: 'answers#add_answer', as: 'new_answer'

  get '/export(.format)', to: 'answers#index', as: 'export'

  namespace :admin do
    root 'base#index'
    resources :users
    get '/config', to: 'config#index', as: 'config'
    post '/config/types', to: 'config#update_types', as: 'config_types'
    post '/config/questions', to: 'config#update_questions', as: 'config_questions'
    delete '/config', to: 'config#purge', as: 'purge_config'
  end
end

lib/annotamele/foundation/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  serialize :body

  validates_presence_of :user_id, :question_id, :body
  before_save :type_validation

  def preprocess
    self.body = question.type.preprocess(body)
  end

  private

  def type_validation
    question.type.validation(body)
  end
end

lib/annotamele/foundation/app/models/answer_types/answer_type.rb
class AnswerType < ActiveRecord::Base
  serialize :body

  self.inheritance_column = :type

  class << self
    attr_accessor :custom_fields_list, :validations, :preprocesses
  end

  def custom_fields_list
    self.class.custom_fields_list || []
  end

  def validations
    self.class.validations || []
  end

  def preprocesses
    self.class.preprocesses || []
  end

  def self.custom_fields(*args)
    args.each do |arg|
      (@custom_fields_list ||= []) << arg
      class_eval "def #{arg}; body[:#{arg}];end"
      class_eval "def #{arg}=(val);body[:#{arg}]=val;end"
    end
  end

  def self.preprocess_answer(&block)
    (@preprocesses ||= []) << block
  end

  def self.validate_answer(&block)
    (@validations ||= []) << block
  end

  def view_partial
    {
      partial: "answer_types/#{self.class.to_s.underscore}",
      locals: export
    }
  end

  def export
    custom_fields_list.each_with_object(type: self.class.name) do |field, total|
      total[field] = body[field]
    end
  end

  def preprocess(answer)
    preprocesses.inject(answer) do |res, callback|
      instance_exec res, &callback
    end
  end

  def validation(answer)
    validations.all? do |callback|
      instance_exec answer, &callback
    end
  end
end

lib/annotamele/foundation/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authenticate_user!

  def question
    @question = Question.random_without(current_user.answered_question_ids).first

    respond_to do |format|
      format.html { render :new }
    end
  end

  def add_answer
    @answer = Answer.new(answer_params)
    @answer.user = current_user || User.anonymous
    @answer.preprocess

    if @answer.save
      redirect_to new_question_path
    else
      redirect_to new_question_path, alert: 'Your answer was not valid'
    end
  end

  def index
    @answers = Answer.includes(:question).all

    render :index, formats: :json
  end

  private

  def answer_params
    params.require(:answer).permit!
  end
end

lib/annotamele/foundation/app/views/answers/_multilabel.html.erb
<% if options && text %>
  <div class="form-group">
    <label><%= text %></label>

    <div class="" data-toggle="buttons">
      <% options.each do |option| %>
        <label class="btn btn-info">
          <input type="checkbox" name="answer[body][]" value="<%= option %>" autocomplete="off" /><%= option %>
        </label>
      <% end %>
    </div>
  </div>
<% end %>

lib/annotamele/foundation/app/views/answers/_singlelabel.html.erb
<% if options && text %>
  <div class="form-group">
    <label><%= text %></label>

    <div class="" data-toggle="buttons">
      <% options.each do |option| %>
        <label class="btn btn-info">
          <input type="radio" name="answer[body][]" value="<%= option %>" autocomplete="off" /><%= option %>
        </label>
      <% end %>
    </div>
  </div>
<% end %>

lib/annotamele/foundation/app/views/answers/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-primary">
    <div class="panel-body">
      <% if @question %>
        <%= form_tag new_answer_path do %>
          <input type="hidden" id="question_id" name="answer[question_id]" value="<%= @question.id %>" />

          <div class="form-group">
            <label><%= @question.object %></label>
          </div>

          <div class="form-group">
            <label>Context</label>
            <pre><%=raw @question.context %></pre>
          </div>

          <%= render @question.type.view_partial %>

          <br />
          <%= submit_tag 'Submit', class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <h2>Looks like no more questions left</h2>
      <% end%>
    </div>
  </div>
</div>