lib/annotamele/foundation/config/routes.rb
AnnotameLE::Application.routes.draw do
  devise_for :users

  root 'answers#question'

  get '/question', to: 'answers#question', as: 'new_question'
  post '/answer', to: 'answers#add_answer', as: 'new_answer'

  get '/export(.format)', to: 'answers#index', as: 'export'

  namespace :admin do
    root 'base#index'
    resources :users
    get '/config', to: 'config#index', as: 'config'
    post '/config/types', to: 'config#update_types', as: 'config_types'
    post '/config/questions', to: 'config#update_questions', as: 'config_questions'
    delete '/config', to: 'config#purge', as: 'purge_config'
  end
end

lib/annotamele/foundation/app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_filter :require_admin!

    def index
      @last_signups = User.last_signups(10)
      @last_signins = User.last_signins(10)
      @user_count = User.users_count
      @answer_count = Answer.count
    end
  end
end

lib/annotamele/foundation/app/views/admin/base/index.html.erb
<% title("Admin Panel") %>
<ol class="breadcrumb">
  <li>Admin Panel</li>
</ol>
<div class="row">
  <div class="col-sm-4">
    <h3>Menu</h3>
    <h4><%= link_to "Export", export_path %> <small>- <%= pluralize(@answer_count, 'answer') %></small></h4>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= pluralize(@user_count, 'user') %></small></h4>
    <h4><%= link_to "Config", admin_config_path %></h4>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>

</div>